version: '3'
services:
     thiea_test_dev:
           image: theiaide/theia:latest
           volumes:
              - .:/home/project
           ports:
              - "5500:3000"
           user: node
